// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: verTqurZzkaRSaGwvFXmnc
// Component: mSIdBRkJtwB
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_torneio_entre_festas.module.css"; // plasmic-import: verTqurZzkaRSaGwvFXmnc/projectcss
import sty from "./PlasmicMatchTableRow.module.css"; // plasmic-import: mSIdBRkJtwB/css

export type PlasmicMatchTableRow__VariantMembers = {};

export type PlasmicMatchTableRow__VariantsArgs = {};
type VariantPropType = keyof PlasmicMatchTableRow__VariantsArgs;
export const PlasmicMatchTableRow__VariantProps = new Array<VariantPropType>();

export type PlasmicMatchTableRow__ArgsType = {};
type ArgPropType = keyof PlasmicMatchTableRow__ArgsType;
export const PlasmicMatchTableRow__ArgProps = new Array<ArgPropType>();

export type PlasmicMatchTableRow__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultMatchTableRowProps {
  className?: string;
}

function PlasmicMatchTableRow__RenderFunc(props: {
  variants: PlasmicMatchTableRow__VariantsArgs;
  args: PlasmicMatchTableRow__ArgsType;
  overrides: PlasmicMatchTableRow__OverridesType;
  dataFetches?: PlasmicMatchTableRow__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__p0ZT1)}
      >
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__waN7E)}>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {"Crispiniano"}
            </div>
          </div>
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox___2R1Ts)} />
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__tPrQd)} />
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__odVWf)} />
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__fJZ)} />
        ) : null}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMatchTableRow__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMatchTableRow__VariantsArgs;
    args?: PlasmicMatchTableRow__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMatchTableRow__Fetches;
  } & Omit<PlasmicMatchTableRow__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMatchTableRow__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMatchTableRow__ArgProps,
      internalVariantPropNames: PlasmicMatchTableRow__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMatchTableRow__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMatchTableRow";
  } else {
    func.displayName = `PlasmicMatchTableRow.${nodeName}`;
  }
  return func;
}

export const PlasmicMatchTableRow = Object.assign(
  // Top-level PlasmicMatchTableRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicMatchTableRow
    internalVariantProps: PlasmicMatchTableRow__VariantProps,
    internalArgProps: PlasmicMatchTableRow__ArgProps
  }
);

export default PlasmicMatchTableRow;
/* prettier-ignore-end */
