// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: verTqurZzkaRSaGwvFXmnc
// Component: PaLU3rBawjK
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MatchTableRow from "../../MatchTableRow"; // plasmic-import: mSIdBRkJtwB/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_torneio_entre_festas.module.css"; // plasmic-import: verTqurZzkaRSaGwvFXmnc/projectcss
import sty from "./PlasmicMatchTable.module.css"; // plasmic-import: PaLU3rBawjK/css

export type PlasmicMatchTable__VariantMembers = {};

export type PlasmicMatchTable__VariantsArgs = {};
type VariantPropType = keyof PlasmicMatchTable__VariantsArgs;
export const PlasmicMatchTable__VariantProps = new Array<VariantPropType>();

export type PlasmicMatchTable__ArgsType = {};
type ArgPropType = keyof PlasmicMatchTable__ArgsType;
export const PlasmicMatchTable__ArgProps = new Array<ArgPropType>();

export type PlasmicMatchTable__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMatchTableProps {
  className?: string;
}

function PlasmicMatchTable__RenderFunc(props: {
  variants: PlasmicMatchTable__VariantsArgs;
  args: PlasmicMatchTable__ArgsType;
  overrides: PlasmicMatchTable__OverridesType;
  dataFetches?: PlasmicMatchTable__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___0PrIx)}
      >
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__jjcKr)} />
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__lgNgh)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qt50S
              )}
            >
              {"Crispiniano"}
            </div>
          </div>
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox___85LHl)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ob874
              )}
            >
              {"Fabio"}
            </div>
          </div>
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox__zkq8F)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nrKEv
              )}
            >
              {"Gabriel"}
            </div>
          </div>
        ) : null}
        {true ? (
          <div className={classNames(projectcss.all, sty.freeBox___2Yq)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__alrL
              )}
            >
              {"Marcelo"}
            </div>
          </div>
        ) : null}
      </p.Stack>

      <MatchTableRow
        className={classNames("__wab_instance", sty.matchTableRow__bRju8)}
      />

      <MatchTableRow
        className={classNames("__wab_instance", sty.matchTableRow__ko6ST)}
      />

      <MatchTableRow
        className={classNames("__wab_instance", sty.matchTableRow__h7AYh)}
      />

      <MatchTableRow
        className={classNames("__wab_instance", sty.matchTableRow__quyOm)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMatchTable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMatchTable__VariantsArgs;
    args?: PlasmicMatchTable__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMatchTable__Fetches;
  } & Omit<PlasmicMatchTable__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMatchTable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMatchTable__ArgProps,
      internalVariantPropNames: PlasmicMatchTable__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMatchTable__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMatchTable";
  } else {
    func.displayName = `PlasmicMatchTable.${nodeName}`;
  }
  return func;
}

export const PlasmicMatchTable = Object.assign(
  // Top-level PlasmicMatchTable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMatchTable
    internalVariantProps: PlasmicMatchTable__VariantProps,
    internalArgProps: PlasmicMatchTable__ArgProps
  }
);

export default PlasmicMatchTable;
/* prettier-ignore-end */
